#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server with requirements

# Check for the number of arguments passed

if [ $# -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Get the arguments
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Disable strict host key checking (not recommended for production)
if [ -f "$file_path" ]; then
  scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip":~/
  # scp -i $ssh_key $file_path $username@$server_ip:~/ 
fi
# OR
# Construct the scp command with arguments
# scp_command="scp -r -i '$ssh_key' '$file_path' $username@$server_ip:~/ "
# Execute the scp command
# $scp_command
