#!/usr/bin/env bash
# configures a brand new Ubuntu machine to the requirements:
# Configure your Nginx server to have a custom 404 page that contains the string `Ceci n'est pas une page`.

# Exit immediately if a command exits with a non-zero status
# set -e

# Update package index//list and install Nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Start Nginx service
sudo service nginx start

# Allow OpenSSH and Nginx HTTP traffic through the firewall
# sudo ufw allow 'OpenSSH'
# sudo ufw allow 'Nginx HTTP'

sudo echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html

# Create a custom HTML file for the 404 page
sudo echo "<html><head></head><body></body></html>" | sudo tee /var/www/html/error_404.html

# Pass the desired string into the HTML file
sudo sed -i "/<body>/a \    Ceci n'est pas une page" /var/www/html/error_404.html

# Create a custom HTML file to handle the redirect
sudo echo "<html><head><meta http-equiv=\"refresh\" content=\"0; URL='https://github.com/OluTshegz'\" /></head><body></body></html>" | sudo tee /var/www/html/redirect_me.html

# Configure Nginx to use the custom 404 page and handle the redirect
sudo sed -i '/listen 80 default_server;/a error_page 404 /error_404.html;\n\nlocation /redirect_me {\n    return 301 /redirect.html;\n}' /etc/nginx/sites-available/default

# Restart Nginx service to apply the configuration changes
sudo service nginx restart
