#!/usr/bin/env bash
# configures a brand new Ubuntu machine to the requirements:
# Configure your Nginx server so that `/redirect_me` is redirecting to another page

# Exit immediately if a command exits with a non-zero status
# set -e

# Update package index//list and install Nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Start Nginx service
sudo service nginx start

# Allow OpenSSH and Nginx HTTP traffic through the firewall
# sudo ufw allow 'OpenSSH'
# sudo ufw allow 'Nginx HTTP'

sudo echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html

# Create a custom HTML file for the 404 page
sudo echo "<html><body>Ceci n'est pas une page</body></html>" | sudo tee /var/www/html/error_404.html

# Configure Nginx to use the custom 404 page
sudo sed -i '/listen 80 default_server;/a error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# Restart Nginx service to apply the configuration changes
sudo service nginx restart
