#!/usr/bin/env bash
# configures a brand new Ubuntu machine to the requirements
# Configure Nginx so that its HTTP response contains a custom header (on `web-01` and `web-02`)
# The name of the custom HTTP header must be `X-Served-By`
# The value of the custom HTTP header must be the hostname of the server Nginx is running on
sudo apt-get update -y
sudo apt-get install -y nginx
sudo service nginx start
HOSTNAME=$(hostname)
sudo sed -i "/http {/a\         add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo nginx -t
sudo service nginx restart
