#!/usr/bin/env bash
# configures a new Ubuntu machine to respect requirements:
# Install and configure HAproxy on your `lb-01` server
# Configure HAproxy so that it send traffic to `web-01` and `web-02`
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

# Install HAproxy
sudo apt-get update -y
# sudo apt-get install -y --no-install-recommends software-properties-common
# sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
# sudo apt-get install -y haproxy=2.8.\*
sudo apt-get install -y haproxy

# Configure HAproxy
config_server="
frontend olutshegz.tech-frontend
        bind *:80
        mode http
        default_backend olutshegz.tech-backend

backend olutshegz.tech-backend
        balance roundrobin
        server 530478-web-01 52.91.126.218:80 check
        server 530478-web-02 54.89.178.237:80 check"
echo "$config_server" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart HAproxy to apply the configuration
sudo service haproxy restart
