#!/usr/bin/env bash
# This bash script pings an IP address passed as an argument.
# Accepts a string as an argument
# Displays `Usage: 5-is_the_host_on_the_network {IP_ADDRESS}` if no argument passed
# Ping the IP 5 times

# ip variable
ip="${1}"

# file name
file=$(basename "${BASH_SOURCE[@]}")

if ! [ "$ip" ]; then
    echo "Usage: ${file} {IP_ADDRESS}"
else
    ping -c 5 "${ip}"
fi
