#!/usr/bin/env bash
# This script is used to configure Nginx to listen on port 80.
# By default, Nginx listens on port 80, but sometimes
# it may not be configured correctly.
# This script ensures that Nginx is configured to listen on
# port 80 by modifying the Nginx configuration file.
# Usage: ./0-nginx_likes_port_80
# Note: This script requires root privileges to modify the Nginx configuration file.
# steps to solve it: delete the existing ../sites-enabled/default and replace it with a copy of
# ../sites-available/default. You do that by creating a symbolic link. 
# NB: The flag -s creates a symbolic link, -f deletes the existing file and replaces it
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
