#!/usr/bin/env bash
# Using your previous exercise command, write a Bash script
# that displays lines containing the bash word, thus
# allowing you to easily get the PID of your Bash process.
# Requirements:
# You cannot use `pgrep`
# The third line of your script must be `# shellcheck disable=SC2009`

# Example: Here we can see that my Bash PID is 4404.

ps -aux | grep bash
