#!/usr/bin/env bash
# Write a Bash script that displays the PID, along with the
# process name, of processes whose name contain the word `bash`.
# Requirements:
# You cannot use `ps`

# Example. Here we can see that:
# For the first iteration: bash PID is 4404 and that the 3-show_your_bash_pid_made_easy script PID is 4555
# For the second iteration: bash PID is 4404 and that the 3-show_your_bash_pid_made_easy script PID is 4557

pgrep -l bash
