#!/usr/bin/env bash
# Write a Bash script that stops 4-to_infinity_and_beyond process.
# Requirements:
# You must use `kill`

# We stopped our `4-to_infinity_and_beyond` process using `ctrl+c`
# in the previous task, there is actually another way to do this.
# I opened 2 terminals in this example, started by running my `4-to_infinity_and_beyond`
# Bash script in terminal #0 and then moved on terminal #1 to run `5-dont_stop_me_now`.
# We can then see in terminal #0 that my process has been terminated.

kill "$(pgrep -f 4-to_infinity_and_beyond)"
