#!/usr/bin/env bash
# Write a Bash script that displays:
# `To infinity and beyond` indefinitely
# With a `sleep 2` in between each iteration
# `I am invincible!!!` when receiving a `SIGTERM` signal

# Make a copy of your `6-stop_me_if_you_can script`, name it `67-stop_me_if_you_can`,
# that kills the `7-highlander` process instead of the `4-to_infinity_and_beyond` one.
# I started `7-highlander` in Terminal #0 and then run `67-stop_me_if_you_can`
# in terminal #1, for every iteration we can see `I am invincible!!!` appearing in terminal #0.

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I am invincible!!!"' SIGTERM
done
