#!/usr/bin/env bash
# This script is displaying "Best School" 10 times.
# Write a Bash script that displays `Best School` 10 times.
# use the `for` loop only.

for ((i = 0; i < 10; i++))
do
    echo "Best School"
done
