#!/usr/bin/env bash
# Write a Bash script that displays the content of the file `/etc/passwd`.
# Your script should only display:
# username
# user id
# Home directory path for the user
# Requirements:
# You must use the while loop (for and until are forbidden)

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
