#!/usr/bin/env bash
# Write a Bash script that displays the content of
# the file /etc/passwd, using the while loop + IFS.
# Format: ```The user USERNAME is part of the GROUP_ID gang,
# lives in HOME_DIRECTORY and rides COMMAND/SHELL.
# USER ID's place is protected by the passcode PASSWORD,
# more info about the user here: USER ID INFO```
# Requirements:
# You must use the while loop (for and until are forbidden)

while IFS=':' read -r username password uid gid info home shell; do
  echo "The user $username is part of the $gid gang,"\
  "lives in $home and rides $shell."\
  "$uid's place is protected by the passcode $password,"\
  "more info about the user here: $info"
done < "/etc/passwd"
