#!/usr/bin/env bash
# Write a Bash script that displays `Best School` 10 times,
# but for the 9th iteration, displays `Best School`
# and then `Hi` on a new line.
# use the `while` loop and the `if` statement only

i=1

while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    i=$(( i + 1 ))
done
