#!/usr/bin/env bash
# This bash script that configures an Ubuntu server that resolves:
# `localhost` to `127.0.0.2`
# `facebook.com` to `8.8.8.8`
# This changes the IP configuration of `localhost` and `facebook`
# cat `/etc/hosts`

# Copy the existing `/etc/hosts` file to a new file called `~/hosts.new`
# Write the new IP address and hostname to the `~/hosts.new` file
# sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new (in-place substitute first option with second)
# adding (appending) at the second line '8.8.8.8 facebook.com'
# sed -i '2i8.8.8.8 facebook.com' ~/hosts.new (in-place adding to second line)
# Copy the `~/hosts.new` file to the `/etc/hosts` file

cp /etc/hosts ~/hosts.new
echo "127.0.0.2 localhost" > ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
