#!/usr/bin/env bash
# This script ensures nginx is running as the nginx user, listens on all active IPs on port 8080, and does not use apt-get remove

# Adds system user 'nginx' without home directory, login, and assigns it to the 'nginx' group
sudo adduser --system --no-create-home --disabled-login --group nginx

# Set nginx user in the config by replacing '#user' and its value
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Replace port 80 with 8080 in the sites-available config
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Change ownership of the Nginx directory (/usr/share/nginx) to the nginx user and group
chown -R nginx:nginx /usr/share/nginx

# Give owner permissions to read and write to the config file
sudo chmod 644 /etc/nginx/nginx.conf

# Stop Apache if it's running
sudo service apache2 stop
# OR Kill the apache process
# pkill apache2

# Ensure nginx service is enabled to start on system boot
sudo systemctl enable nginx

# Restart the nginx service as the nginx user
sudo -u nginx service nginx restart
