#!/usr/bin/env bash
# a Bash script that uses `ssh` to connect to your server using
# the private key `~/.ssh/school` with the user `ubuntu`

# Server address
SERVER="52.91.126.218"
# Connect to the server using SSH with single-character flags
ssh -i ~/.ssh/school ubuntu@$SERVER
